export const ToolFailureCode = {
  INVALID_INPUT: "INVALID_INPUT",
  UNKNOWN_TOOL: "UNKNOWN_TOOL",
  ABORTED: "ABORTED",
  TIMEOUT: "TIMEOUT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DNS_ERROR: "DNS_ERROR",
  TLS_ERROR: "TLS_ERROR",
  HTTP_403: "HTTP_403",
  HTTP_412: "HTTP_412",
  WAF_BLOCKED: "WAF_BLOCKED",
  ACCESS_DENIED: "ACCESS_DENIED",
  STATIC_CONTENT_EMPTY: "STATIC_CONTENT_EMPTY",
  DYNAMIC_RENDER_REQUIRED: "DYNAMIC_RENDER_REQUIRED",
  REGION_NOT_FOUND: "REGION_NOT_FOUND",
  SEARCH_PROVIDER_NOT_CONFIGURED: "SEARCH_PROVIDER_NOT_CONFIGURED",
  SEARCH_PROVIDER_NOT_FOUND: "SEARCH_PROVIDER_NOT_FOUND",
  SEARCH_AUTH_FAILED: "SEARCH_AUTH_FAILED",
  SEARCH_RATE_LIMITED: "SEARCH_RATE_LIMITED",
  SEARCH_REQUEST_FAILED: "SEARCH_REQUEST_FAILED",
  BROWSER_LAUNCH_FAILED: "BROWSER_LAUNCH_FAILED",
  BROWSER_NAVIGATION_FAILED: "BROWSER_NAVIGATION_FAILED",
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  INVENTORY_ALREADY_SUBMITTED: "INVENTORY_ALREADY_SUBMITTED",
  INVESTIGATION_ALREADY_SUBMITTED: "INVESTIGATION_ALREADY_SUBMITTED",
  INVESTIGATOR_EVIDENCE_ALREADY_SUBMITTED: "INVESTIGATOR_EVIDENCE_ALREADY_SUBMITTED",
  POSITION_CANDIDATE_UNKNOWN_PRIMARY: "POSITION_CANDIDATE_UNKNOWN_PRIMARY",
  POSITION_CANDIDATE_COVERAGE_REQUIRED: "POSITION_CANDIDATE_COVERAGE_REQUIRED",
  PRIMARY_PEOPLE_NOT_DISTINCT: "PRIMARY_PEOPLE_NOT_DISTINCT",
  REVIEW_DECISION_ALREADY_SUBMITTED: "REVIEW_DECISION_ALREADY_SUBMITTED",
  REVIEW_UNKNOWN_PRIMARY_TARGET: "REVIEW_UNKNOWN_PRIMARY_TARGET",
  REVIEW_TARGET_COVERAGE_REQUIRED: "REVIEW_TARGET_COVERAGE_REQUIRED",
  REVIEW_CANDIDATE_NOT_IN_POOL: "REVIEW_CANDIDATE_NOT_IN_POOL",
  REVIEW_OUTCOME_INCONSISTENT: "REVIEW_OUTCOME_INCONSISTENT",
  REVIEW_OBSERVATION_REQUIRED: "REVIEW_OBSERVATION_REQUIRED",
  RECOVERY_ALREADY_SUBMITTED: "RECOVERY_ALREADY_SUBMITTED",
  RECOVERY_CANDIDATE_DUPLICATE: "RECOVERY_CANDIDATE_DUPLICATE",
  RECOVERY_OBSERVATION_REQUIRED: "RECOVERY_OBSERVATION_REQUIRED",
  /** STEP 19.4：submit_investigation 契约修复链专用错误码。 */
  INVESTIGATION_SCHEMA_VALIDATION_FAILED: "INVESTIGATION_SCHEMA_VALIDATION_FAILED",
  INVESTIGATION_SCHEMA_REPAIR_EXHAUSTED: "INVESTIGATION_SCHEMA_REPAIR_EXHAUSTED",
  INVESTIGATION_REPEATED_SCHEMA_ERROR: "INVESTIGATION_REPEATED_SCHEMA_ERROR",
  INVESTIGATION_TOOL_NOT_CALLED: "INVESTIGATION_TOOL_NOT_CALLED",
  INVESTIGATION_PROVIDER_TOOL_CALL_INVALID: "INVESTIGATION_PROVIDER_TOOL_CALL_INVALID",
  RESEARCH_TOOL_NOT_ALLOWED_DURING_SUBMISSION_REPAIR:
    "RESEARCH_TOOL_NOT_ALLOWED_DURING_SUBMISSION_REPAIR",
} as const;

export type ToolFailureCode = (typeof ToolFailureCode)[keyof typeof ToolFailureCode];

export type ToolFailure = {
  code: ToolFailureCode;
  message: string;
  retryable: boolean;
  /** STEP 19.4：结构化修复详情（ValidationIssue[]），供 Runner 生成精确 repair
   *  反馈。不含完整 payload / secrets / reasoning。 */
  details?: unknown;
};

export class ToolFailureError extends Error {
  readonly code: ToolFailureCode;
  readonly retryable: boolean;
  readonly details?: unknown;

  constructor(failure: ToolFailure) {
    super(failure.message);
    this.name = "ToolFailureError";
    this.code = failure.code;
    this.retryable = failure.retryable;
    this.details = failure.details;
  }

  toFailure(): ToolFailure {
    return {
      code: this.code,
      message: this.message,
      retryable: this.retryable,
      ...(this.details !== undefined ? { details: this.details } : {}),
    };
  }
}
